"""Processing report generation for each task."""
from __future__ import annotations

from pathlib import Path

from .package import (
    load_manifest,
    get_processing_runs,
    get_quality_flags,
    get_relationships,
    get_review_records,
)


def generate_processing_report(task_dir: Path) -> str:
    manifest = load_manifest(task_dir)
    if not manifest:
        return ""

    runs = get_processing_runs(task_dir)
    flags = get_quality_flags(task_dir)
    rels = get_relationships(task_dir)
    reviews = get_review_records(task_dir)

    raw_files = sorted((task_dir / "raw").glob("*"))
    derived_files = sorted((task_dir / "derived").glob("*"))

    lines = [
        f"# Processing Report: {task_dir.name}",
        "",
        "> **IMPORTANT**: This report does NOT contain scientific conclusions.",
        "> It contains only factual observations, statistical trends, and processing risks.",
        "",
        "## Input Files",
    ]

    for f in raw_files:
        if not f.name.startswith("."):
            lines.append(f"- {f.name} ({f.stat().st_size} bytes)")

    lines.append("")
    lines.append("## Derived Output Files")
    for f in derived_files:
        if not f.name.startswith("."):
            lines.append(f"- {f.name}")

    lines.append("")
    lines.append("## Processing Runs")
    for run in runs:
        status = run.get("status", "unknown")
        tool = run.get("tool_name", "unknown")
        warnings = run.get("warnings", [])
        errors = run.get("errors", [])
        lines.append(f"- **{tool}**: {status}")
        if warnings:
            for w in warnings:
                lines.append(f"  - Warning: {w}")
        if errors:
            for e in errors:
                lines.append(f"  - Error: {e}")

    lines.append("")
    lines.append("## Quality Flags")
    for flag in flags:
        severity = flag.get("severity", "info")
        message = flag.get("message", "")
        requires_review = flag.get("requires_review", False)
        review_mark = " [REVIEW REQUIRED]" if requires_review else ""
        lines.append(f"- [{severity.upper()}]{review_mark} {message}")

    lines.append("")
    lines.append("## Relationships")
    for rel in rels:
        rel_type = rel.get("rel_type", "")
        source = rel.get("source_id", "")[:8]
        target = rel.get("target_id", "")[:8]
        lines.append(f"- {rel_type}: {source}... -> {target}...")

    lines.append("")
    lines.append("## Review Status")
    if reviews:
        for rev in reviews:
            action = rev.get("action", "")
            reviewer = rev.get("reviewer", "")
            comment = rev.get("comment", "")
            lines.append(f"- **{action}** by {reviewer}: {comment}")
    else:
        lines.append("- No reviews recorded.")

    lines.append("")
    lines.append("## Disclaimer")
    lines.append("This report is generated by the Material Data Processing Agent.")
    lines.append("All observations are factual or statistical in nature.")
    lines.append("No causal conclusions, mechanistic interpretations, or experimental recommendations are included.")

    report = "\n".join(lines)
    report_path = task_dir / "logs" / "processing_report.md"
    report_path.write_text(report, encoding="utf-8")

    return report
